apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-load-script
  namespace: kafka

data:
  producer.sh: |
    #!/bin/bash
    set -e

    TOPIC="${TOPIC:-load-test-topic}"
    BROKER="${BROKER:-kafka-cluster-kafka-bootstrap:9092}"
    SCENARIO="${SCENARIO:-normal}"

    THROUGHPUT="${THROUGHPUT:--1}"
    RECORD_SIZE="${RECORD_SIZE:-1024}"
    NUM_RECORDS="${NUM_RECORDS:-10000000}"

    echo "Starting Kafka load test"
    echo "Scenario: ${SCENARIO}"
    echo "Broker: ${BROKER}"
    echo "Topic: ${TOPIC}"
    ########################################
    # BREAKDOWN SCENARIO 
    ########################################
    if [ "$SCENARIO" = "breakdown" ]; then
        echo "Running BREAKDOWN scenario"
        RATE=1000
        SECONDS_PER_STEP=40
        
        while true
        do
            COMPUTED_RECORDS=$((RATE * SECONDS_PER_STEP))
            
            echo "Current throughput: $RATE msg/s (Running for ${SECONDS_PER_STEP}s, Total Records: ${COMPUTED_RECORDS})"
            
  
            /opt/kafka/bin/kafka-producer-perf-test.sh \
            --topic "${TOPIC}" \
            --num-records "${NUM_RECORDS}" \
            --throughput "${THROUGHPUT}" \
            --record-size "${RECORD_SIZE}" \
            --producer-props \
                acks=1 \
                bootstrap.servers="${BROKER}" \
  
              
            echo "Step with $RATE msg/s finished. Waiting 5s before next step..."
            sleep 5 
            
            RATE=$((RATE * 2))
            if [ "$RATE" -gt 64000 ]; then
                echo "Max rate reached, stopping breakdown"
                break
            fi
        done
        exit 0
    fi

    ########################################
    # ELSE: DEFAULT 
    ########################################
    /opt/kafka/bin/kafka-producer-perf-test.sh \
      --topic "${TOPIC}" \
      --num-records "${NUM_RECORDS}" \
      --throughput "${THROUGHPUT}" \
      --record-size "${RECORD_SIZE}" \
      --producer-props \
          acks=1 \
          bootstrap.servers="${BROKER}" \
          batch.size=0 \
          linger.ms=0 \
    
    sleep 30
