apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-load-script
  namespace: kafka

data:
  producer.sh: |
    #!/bin/bash
    set -e

    TOPIC="${TOPIC:-load-test-topic}"
    BROKER="${BROKER:-kafka-cluster-kafka-bootstrap:9092}"
    SCENARIO="${SCENARIO:-normal}"

    THROUGHPUT="${THROUGHPUT:--1}"
    RECORD_SIZE="${RECORD_SIZE:-1024}"
    NUM_RECORDS="${NUM_RECORDS:-10000000}"

    echo "Starting Kafka load test"
    echo "Scenario: ${SCENARIO}"
    echo "Broker: ${BROKER}"
    echo "Topic: ${TOPIC}"

    ########################################
    # BREAKDOWN SCENARIO
    ########################################
    if [ "$SCENARIO" = "breakdown" ]; then
      echo "Running BREAKDOWN scenario"

      RATE=1000

    while [ "$RATE" -le 64000 ]
    do
      echo "Rate=$RATE"
    
      timeout 10 \
      /opt/kafka/bin/kafka-producer-perf-test.sh \
          --topic "${TOPIC}" \
          --num-records 100000000 \
          --throughput "${RATE}" \
          --record-size "${RECORD_SIZE}" \
          --producer-props acks=1 bootstrap.servers="${BROKER}"
    
      RATE=$((RATE * 2))
    done

    ########################################
    # ELSE: DEFAULT 
    ########################################
    /opt/kafka/bin/kafka-producer-perf-test.sh \
      --topic "${TOPIC}" \
      --num-records "${NUM_RECORDS}" \
      --throughput "${THROUGHPUT}" \
      --record-size "${RECORD_SIZE}" \
      --producer-props acks=1 bootstrap.servers="${BROKER}"