apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-cpu-stress
  namespace: kafka
spec:
  mode: fixed
  value: '1'
  selector:
    namespaces:
      - kafka
    labelSelectors:
      'strimzi.io/kind': 'stu245087-kafka-cluster-kafka'
  stressors:
    cpu:
      workers: 2
      load: 85
  duration: '40s'