apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-broker-failure
  namespace: kafka
spec:
  action: pod-failure
  mode: fixed
  value: '1'
  duration: '40s' # Passt perfekt zu deinen 40s Benchmark-Stufen
  selector:
    namespaces:
      - kafka
    labelSelectors:
      'strimzi.io/kind': 'stu245087-kafka-cluster-kafka'