apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-minimal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 83.0.0
    helm:
      values: |
        alertmanager:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        prometheusOperator:
          enabled: true
        prometheus:
          enabled: true
          service:
            type: NodePort
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            scrapeInterval: 1s
        grafana:
          enabled: false
        defaultRules:
          create: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true